# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='product',
            field=models.CharField(default='widjdwd', max_length=50),
            preserve_default=False,
        ),
    ]
